### ISSUE TITLE
Bug: Custom context menu can cover titlebar buttons like minimize/maximize/close.

### ISSUE THREAD

**Issue by Alloyd031** [Gaoyifei1011/WinUI3WindowMenuStyle#1]
I right-clicked the titlebar buttons and they got covered by the custom context menu.

**Comment by Gaoyifei1011** [comment]
> I right-clicked the titlebar buttons and they got covered by the custom context menu.

https://github.com/Gaoyifei1011/WinUI3WindowMenuStyle/commit/0a22b0df7bd4c27a91a14c42d588cfedc3adbab6
![{A6AAE15E-8479-46C2-A0A7-5884C13DCFA0}](https://github.com/user-attachments/assets/a0c853b0-2ad0-4712-a1e2-49aef195192d)

WM_NCRBUTTONUP 错误的消息已经修复
WM_NCRBUTTONUP error message has been fixed

**Comment by Alloyd031** [comment]
Now the app just crashes

**Comment by Alloyd031** [comment]
Nvm, i fixed the crash
