### ISSUE TITLE
Restore is Always Disabled and Maximize is Always Enabled

### ISSUE THREAD

**Issue by ghost1372** [Gaoyifei1011/WinUI3WindowMenuStyle#2]
Buttons disabled and enabled all wrongs
![image](https://github.com/user-attachments/assets/09123eb2-6770-42c2-80e0-f302745f783f)

---

Visual Studio and File Explorer in Maximized state:

Move, Size, Maximize should be disabled
Restore should be enabled

![image](https://github.com/user-attachments/assets/cef98fe4-1019-418a-bf54-f3fdf80130b4)

**Comment by Gaoyifei1011** [comment]
> Buttons disabled and enabled all wrongs ![image](https://private-user-images.githubusercontent.com/9213496/353777658-09123eb2-6770-42c2-80e0-f302745f783f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODI0OTEsIm5iZiI6MTcyMjQ4MjE5MSwicGF0aCI6Ii85MjEzNDk2LzM1Mzc3NzY1OC0wOTEyM2ViMi02NzcwLTQyYzItODBlMC1mMzAyNzQ1Zjc4M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMDMxNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhiZGI0OTlkZDNmODc5NzU4ZDAxN2I1MWU4NWZlMjU1YzY2NmRhOGZlZjk4MzE0MDZiZjM2Y2ZmODkwZGI4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.q1NOMOav14zOZM1KNgD59Io0JZ51ffm_2o1xqkHPdkc)
> 
> Visual Studio and File Explorer in Maximized state:
> 
> Move, Size, Maximize should be disabled Restore should be enabled
> 
> ![image](https://private-user-images.githubusercontent.com/9213496/353777998-cef98fe4-1019-418a-bf54-f3fdf80130b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODI0OTEsIm5iZiI6MTcyMjQ4MjE5MSwicGF0aCI6Ii85MjEzNDk2LzM1Mzc3Nzk5OC1jZWY5OGZlNC0xMDE5LTQxOGEtYmY1NC1mM2ZkZjgwMTMwYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMDMxNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTE1ODgxZGU3NzM2MDE1YjIzNmYyNjJlZTYzN2MxN2FkYTcyZTdlOWUwMjU0OThjNTU5ZTczZjBjMDhjMzkxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SK7KobRrAbivK-YbF0PMAy3TaCi0cpWzCmQy7paeXFg)

Problems have been solved

**Comment by Gaoyifei1011** [comment]
> Buttons disabled and enabled all wrongs ![image](https://private-user-images.githubusercontent.com/9213496/353777658-09123eb2-6770-42c2-80e0-f302745f783f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODI0OTEsIm5iZiI6MTcyMjQ4MjE5MSwicGF0aCI6Ii85MjEzNDk2LzM1Mzc3NzY1OC0wOTEyM2ViMi02NzcwLTQyYzItODBlMC1mMzAyNzQ1Zjc4M2YucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMDMxNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODhiZGI0OTlkZDNmODc5NzU4ZDAxN2I1MWU4NWZlMjU1YzY2NmRhOGZlZjk4MzE0MDZiZjM2Y2ZmODkwZGI4OSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.q1NOMOav14zOZM1KNgD59Io0JZ51ffm_2o1xqkHPdkc)
> 
> Visual Studio and File Explorer in Maximized state:
> 
> Move, Size, Maximize should be disabled Restore should be enabled
> 
> ![image](https://private-user-images.githubusercontent.com/9213496/353777998-cef98fe4-1019-418a-bf54-f3fdf80130b4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI0ODI0OTEsIm5iZiI6MTcyMjQ4MjE5MSwicGF0aCI6Ii85MjEzNDk2LzM1Mzc3Nzk5OC1jZWY5OGZlNC0xMDE5LTQxOGEtYmY1NC1mM2ZkZjgwMTMwYjQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDFUMDMxNjMxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTE1ODgxZGU3NzM2MDE1YjIzNmYyNjJlZTYzN2MxN2FkYTcyZTdlOWUwMjU0OThjNTU5ZTczZjBjMDhjMzkxOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.SK7KobRrAbivK-YbF0PMAy3TaCi0cpWzCmQy7paeXFg)

Problems have been solved

**Comment by ghost1372** [comment]
Tnx @Gaoyifei1011 
Fixed
